import { Foods } from './foods'

export const FOOD: Foods[] = [
  // { name: 'Cheese Casserole', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 10, image: '../assets/cheesecasserole.jpg'},
  // { name: 'Carrot Cake', description: 'Have you ever wanted to be like Bugs Bunny in the hit TV show Looney Toons?? Well now you can! With this scrumptious treat, you\'ll grow your rabbit ears in no time!', temp_quantity: 0, cart_quantity: 0, price: 8, image: '../assets/carrotcake.jpg'},
  // { name: 'Cantaloupe', description: 'Have you ever tried cantaloupe wrapped in prosciutto? It\'s soooooooo good! But it doesn\'t start with a \"C\", so it doesn\'t belong here.', temp_quantity: 0, cart_quantity: 0, price: 5, image: '../assets/cantaloupe.jpg'},
  // { name: 'Corn Chowder', description: 'Have you ever seen the hit Cartoon Network show, \"Chowder\"? It doesn\'t have anything to do with Corn Chowder, but it was a good show.', temp_quantity: 0, cart_quantity: 0, price: 9, image: '../assets/cornchowder.jpg'},
  // { name: 'Coffee', description: 'Inject yourself with this high-quality performance-enhancing dru-... stimulant! Not only tasty, but extremely effective, too!', temp_quantity: 0, cart_quantity: 0, price: 4, image: '../assets/coffee.jpg'},
  // { name: 'Chicken Chilaquiles', description: 'Why did the chicken cross the road? To get turned into these delicious chicken chilaquiles for you to enjoy! You can taste the cruelty and death in every bite!', temp_quantity: 0, cart_quantity: 0, price: 12, image: '../assets/chickenchilaquiles.jpg'},
  // { name: 'Cheese Casserole', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 10, image: '../assets/cheesecasserole.jpg'},
  // { name: 'Carrot Cake', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 8, image: '../assets/carrotcake.jpg'},
  // { name: 'Cantaloupe', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 5, image: '../assets/cantaloupe.jpg'},
  // { name: 'Corn Chowder', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 9, image: '../assets/cornchowder.jpg'},
  // { name: 'Coffee', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 4, image: '../assets/coffee.jpg'},
  // { name: 'Chicken Chilaquiles', description: 'Enjoy this delectable home-style meal cooked by only the most homely of chefs. This bundle of cheesy goodness will melt your taste buds through the sheer potency of its existence.', temp_quantity: 0, cart_quantity: 0, price: 12, image: '../assets/chickenchilaquiles.jpg'},
]